### ISSUE TITLE
Packer hanging and blocking packets even after unload

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/Packer#2]
I've been trying to narrow down things to figure out how to explain this well enough to hopefully provide you with enough context to try and fix it while also not sounding like idiot. I am giving up on the idiot part.

I can easily force duplicate this inside a mog house, I haven't thoroughly tried at nomad moogles.

If you have packer loaded already (via boot script), once you log in but before your inventory finishes loading, if you are impatient and click the moogle to check your DB out of habit or whatever, you will receive the packer message about blocking packets but at that point packer will hang and never complete processing as well as it will continue to packet block your ability to do stuff (talk to moogle, exit MH). If you then unload packer you still will not be able to talk to moogle like the packets are still being blocked.

After unloading packer if you /logout then go to another char, then reload packer, and be patient this time and not click on anything, everything will work as expected. I should probably state as well that I am not using any direct /pa commands not that it *should* matter, everything is done via luashitacast, so for example after I swap to another char and reload packer to force it to work correctly I just '/lac load' since I already  have something macro'd via crossbar that does that etc etc.

I realize I am rambling at this point so here is a screenshot of the messages I will get when this happens. One more note, on this screenshot, after I unload the addon I am still unable to interact with the moogle or the mog house door as if the packets still being blocked.

![Beane_2022 08 29_113427](https://user-images.githubusercontent.com/66495755/187246004-036abcf6-0e5c-4fe5-9af1-0894f884c440.png)

**Comment by ThornyFFXI** [comment]
I suspect this is caused by the client going into the state where it expects a dialogue response from the moogle, but never getting that dialogue response because the outgoing 0x1A(the action of talking to the moogle) was blocked.  While in this state, the client won't send most outgoing packets(perhaps logout is an exception), so further attempts to talk don't work because of the client's state.

Ideally, I'd prefer not to allow action packets while packer is running, since any adjustment of inventory during mass batch moves could result in side effects or unintended behaviors.  Some actions(such as ninjutsu) use or lock items.  I'll consider adding an exception for talk packets, though you may also crash yourself opening certain menus while packer is running.  Ideally, the user would not try to do anything during operation.  If I'm misunderstanding and this is happening while packer has not yet been started, that's a totally different ball game and I'll need to look into it.

**Comment by ThornyFFXI** [comment]
As an addendum, I've confirmed the behavior does match up with my interpretation of what happens and pushed source(1.13) that will allow talk packets while packer is running, since those are likely the sole exception that will produce that lockup.  I still recommend against trying to do things in the mog house while packer is running(it won't let you open dbox anyway!), but this should at least address the issue of spacing out and forgetting it's currently active.  I will wait for the next ashita beta(which is expected very soon) to push a new release, though obviously you can build from source if able.
